env:
  es6: true
  node: true
  jest: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
overrides:
  - files:
      - "*entity.ts"
    rules:
      camelcase: off
rules:
  "@typescript-eslint/interface-name-prefix":
    - error
    - always
  "@typescript-eslint/ban-types":
    - error
    - types:
        any: null
  "@typescript-eslint/class-name-casing":
    - error
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: false
      allowHigherOrderFunctions: true
  "@typescript-eslint/func-call-spacing":
    - error
  "@typescript-eslint/member-delimiter-style":
    - error
  "@typescript-eslint/no-array-constructor":
    - error
  "@typescript-eslint/no-empty-interface":
    - error
  "@typescript-eslint/no-explicit-any":
    - error
  "@typescript-eslint/no-floating-promises": 2
  "@typescript-eslint/no-magic-numbers":
    - error
    - ignoreNumericLiteralTypes: true
  "@typescript-eslint/no-misused-new":
    - error
  "@typescript-eslint/no-non-null-assertion":
    - error
  "@typescript-eslint/no-unused-vars":
    - error
  "@typescript-eslint/no-use-before-define":
    - error
  "@typescript-eslint/promise-function-async":
    - error
  "@typescript-eslint/semi":
    - error
  "@typescript-eslint/type-annotation-spacing":
    - error
  # best practices
  no-return-await: off

  # stylistic issues
  block-spacing:
    - error
    - always
  camelcase:
    - error
    - properties: never
      ignoreDestructuring: true
  comma-dangle:
    - error
    - never
  func-call-spacing:
    - error
    - never
  indent:
    - error
    - 2
  max-len:
    - warn
    - code: 120
      ignoreComments: true
      ignoreRegExpLiterals: true
      ignoreStrings: false
      ignoreTemplateLiterals: false
      ignoreTrailingComments: true
      ignoreUrls: true
  no-tabs:
    - error
  no-unneeded-ternary:
    - error
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  padded-blocks:
    - error
    - blocks: never
      classes: always
      switches: never
  # ECMAScript 6
  no-useless-constructor: off

